#ifndef _GLOBALS_H
#define _GLOBALS_H

#include <genesis.h>

#define EFFECT_OPTION_ID 64
#define EFFECT_OPTION_SIZE 1024
#define EFFECT_OPTION_PRIORITY 1
#define EFFECT_OPTION_CHANNEL SOUND_PCM_CH2

#define EFFECT_HIT_ID 65
#define EFFECT_HIT_SIZE 1536
#define EFFECT_HIT_PRIORITY 2
#define EFFECT_HIT_CHANNEL SOUND_PCM_CH3

#endif